# Generated by Django 3.0.6 on 2020-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_empresa', models.CharField(max_length=50)),
                ('segmentos', models.CharField(choices=[(' ', 'Alimentação'), (' ', 'Bebidas'), (' ', 'Bancário'), (' ', 'Vestuário'), (' ', 'Saúde'), (' ', 'Educação'), (' ', 'Informática'), (' ', 'Outros')], max_length=1)),
                ('telefone_empresarial', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('formacao', models.CharField(choices=[('EF', 'Ensino Fundamental Completo'), ('EFI', 'Ensino Fundamental Incompleto'), ('EM', 'Ensino Médio Completo'), ('EMI', 'Ensino Médio Incompleto'), ('ES', 'Ensino Superior Completo'), ('ES', 'Ensino Superior Incompleto')], max_length=50)),
                ('auto_descricao', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Prefiro não dizer')], max_length=1)),
                ('atributos', models.CharField(max_length=80)),
            ],
        ),
    ]
