# Generated by Django 3.0.6 on 2020-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('formacao', models.CharField(choices=[('EM', 'Ensino Fundamental Completo'), ('EF', 'Ensino Médio Completo'), ('ES', 'Ensino Superior Completo')], max_length=50)),
                ('auto_descricao', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
    ]
